version: 2
updates:
  - package-ecosystem: uv
    directory: /
    groups:
      python-uv-dependencies:
        patterns:
          - '*'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
  - package-ecosystem: pip
    directory: /
    groups:
      python-pip-dependencies:
        patterns:
          - '*'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
  - package-ecosystem: npm
    directory: /
    groups:
      npm-dependencies:
        patterns:
          - '*'
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
  - package-ecosystem: github-actions
    directory: /
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
